# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from Search import Ui_MainWindow
from Search import MyApp
from Scrap import Mainwindow
from SortAll import Sort_Mainwindow


class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 492)
        MainWindow.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 330, 401, 61))
        self.label.setStyleSheet("font: 87 36pt \"Arial Black\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 380, 531, 61))
        self.label_2.setStyleSheet("font: 87 36pt \"Arial Black\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 240, 191, 221))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/C:/Users/JUNCTION/Downloads/download-removebg-preview.png);")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 190, 101, 31))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 20, 101, 31))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 20, 271, 51))
        self.label_4.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"background-color: rgb(255, 85, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 80, 401, 51))
        self.label_5.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"background-color: rgb(170, 85, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 190, 101, 31))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 85, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 190, 101, 31))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(255, 255, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.pushButton_3.clicked.connect(self.SearchScr)
        self.pushButton.clicked.connect(self.ScrapScr)
        self.pushButton_4.clicked.connect(self.SortScr)
       

    def SortScr(self):
          self.window = Sort_Mainwindow()
          self.window.show()

    def SearchScr(self):
        self.ui = Ui_MainWindow()
        self.window = MyApp()
        self.window.show()

    def ScrapScr(self):
        self.window = Mainwindow()
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "\"WELCOME TO"))
        self.label_2.setText(_translate("MainWindow", "LITERAL INSIGHTS\""))
        self.pushButton.setText(_translate("MainWindow", "SCRAPING"))
        self.pushButton_2.setText(_translate("MainWindow", "EXIT"))
        self.label_4.setText(_translate("MainWindow", "DSA PROJECT"))
        self.label_5.setText(_translate("MainWindow", "CREATED BY: IJK GROUP"))
        self.pushButton_3.setText(_translate("MainWindow", "SEARCHING"))
        self.pushButton_4.setText(_translate("MainWindow", "SORTING"))
#import PROJECTIMAGES_rc
class Welcome(QtWidgets.QMainWindow):
    def __init__(self):
        super(Welcome, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        # self.load_table()
        # self.ui.pushButton.clicked.connect(self.on_search_clicked)

        self.ui.pushButton_2.clicked.connect(lambda: self.close())
        # self.ui.comboBox.currentIndexChanged.connect(self.on_attribute_selected)







if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = Welcome()
    window.show()
    sys.exit(app.exec_())